### ISSUE TITLE
Port to 1.19.3?

### ISSUE THREAD

**Issue by ghost** [Urokhtor/container-tooltips#3]
Hey, I have a back-port request for the “Container Tooltips” mod of yours. Is it ok if you back-port the mod to the specified version, in this issue’s title?

**Comment by Urokhtor** [comment]
I can take a look. If there have not been any major changes in the API, it would be probably pretty straightforward to implement.

**Comment by ghost** [comment]
Alright, thanks!

**Comment by Urokhtor** [comment]
Sorry for the slow response. But I did take a look at backporting this mod to 1.19.3. Unfortunately it isn't as straightforward as I had hoped. There are quite a few changes between 1.19 and 1.20, which means I would have to write quite a bit of rendering code. So I will have to decline this request.

**Comment by ghost** [comment]
Oh - Ok. Thanks for responding, Jere Teitteinen.
